const axios = require('axios');

/**
 * MCQ Generation Service
 * This service takes extracted text, interacts with a third-party LLM/NLP API (e.g., OpenAI),
 * and returns an array of MCQ objects.
 */
require('dotenv').config();

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const OPENAI_ENDPOINT = process.env.OPENAI_ENDPOINT || 'https://api.openai.com/v1/chat/completions';
const MODEL = process.env.OPENAI_MODEL || 'gpt-3.5-turbo';
const MAX_QUESTIONS = parseInt(process.env.MCQ_MAX_QUESTIONS, 10) || 10;

// PUBLIC_INTERFACE
exports.generateMCQsFromText = async function (text, options = {}) {
  /**
   * Generates MCQs from provided plain text using a third-party LLM/NLP API.
   * @param {string} text - Extracted text content (e.g. from a PDF or DOCX file)
   * @param {object} options - { maxQuestions: number, language: string (optional) }
   * @returns {Promise<Array>} - Array of MCQ objects, or throws error
   */
  if (!OPENAI_API_KEY) {
    throw new Error('Missing OpenAI API key in environment variable OPENAI_API_KEY');
  }
  if (!text || typeof text !== 'string' || text.trim().length < 50) {
    throw new Error('Text content is required and must have sufficient length for MCQ generation');
  }

  const maxQuestions = options.maxQuestions || MAX_QUESTIONS;
  const language = options.language || 'English';

  // System prompt for MCQ generation
  const prompt = `
Generate ${maxQuestions} multiple-choice questions (MCQs) based on the following study material. 
Each question should have:
- one correct answer
- three plausible but incorrect distractors (choices)
- Provide the full question (as "question"), a "choices" array, and mark "answer" with the correct answer text.
Format output as a valid JSON array of objects, each with: question, choices, answer.

Study material:
'''${text.trim().substring(0, 3900)}'''
`;

  try {
    const apiResponse = await axios.post(
      OPENAI_ENDPOINT,
      {
        model: MODEL,
        messages: [
          { role: 'system', content: 'You are a helpful assistant that generates MCQs for students.' },
          { role: 'user', content: prompt }
        ],
        temperature: 0.7,
        max_tokens: 1800,
        n: 1,
      },
      {
        headers: {
          'Authorization': `Bearer ${OPENAI_API_KEY}`,
          'Content-Type': 'application/json'
        },
        timeout: 60000
      }
    );

    let llmText;
    if (
      apiResponse.data &&
      apiResponse.data.choices &&
      Array.isArray(apiResponse.data.choices) &&
      apiResponse.data.choices[0].message
    ) {
      llmText = apiResponse.data.choices[0].message.content.trim();
    } else {
      throw new Error('Invalid response format from LLM');
    }

    // Try to parse and validate output
    let mcqs;
    try {
      // Remove code block if present (for OpenAI JSON output)
      if (llmText.startsWith('```json')) {
        llmText = llmText.replace(/^```json|```$/g, '').trim();
      } else if (llmText.startsWith('```')) {
        llmText = llmText.replace(/^```|```$/g, '').trim();
      }
      mcqs = JSON.parse(llmText);
    } catch (err) {
      throw new Error('The MCQ generation API did not return valid JSON. Response: ' + (llmText || '[empty]'));
    }

    // Validate and sanitize MCQs array
    if (!Array.isArray(mcqs) || mcqs.length === 0) {
      throw new Error('No MCQs were generated by the API');
    }

    const validMCQs = mcqs
      .slice(0, maxQuestions)
      .map((item) => ({
        question: typeof item.question === 'string' ? item.question.trim() : '',
        choices: Array.isArray(item.choices) ? item.choices.map(c => c && typeof c === 'string' ? c.trim() : '') : [],
        answer: typeof item.answer === 'string' ? item.answer.trim() : ''
      }))
      .filter(
        (item) => item.question && item.choices && Array.isArray(item.choices) && item.choices.length >= 2 && item.answer
      );

    if (validMCQs.length === 0) {
      throw new Error('No valid MCQs were parsed from API response');
    }

    return validMCQs;
  } catch (err) {
    if (err.response && err.response.data && err.response.data.error) {
      throw new Error('MCQ API error: ' + err.response.data.error.message);
    }
    throw err;
  }
};
