const express = require('express');
const healthController = require('../controllers/health');
const uploadController = require('../controllers/upload');
const mcqController = require('../controllers/mcq');
const upload = require('../middleware/upload');
const quizController = require('../controllers/quiz');

const router = express.Router();
// Health endpoint

/**
 * @swagger
 * /:
 *   get:
 *     summary: Health endpoint
 *     responses:
 *       200:
 *         description: Service health check passed
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: ok
 *                 message:
 *                   type: string
 *                   example: Service is healthy
 *                 timestamp:
 *                   type: string
 *                   format: date-time
 *                 environment:
 *                   type: string
 *                   example: development
 */
router.get('/', healthController.check.bind(healthController));

/**
 * @swagger
 * /upload:
 *   post:
 *     summary: Upload a PDF or DOCX file and extract its text content.
 *     description: >
 *       Accepts a single PDF or DOCX file upload. The response includes metadata describing the uploaded file and the extracted plain text content, if successfully extracted.
 *       Also indicates content extraction errors if extraction fails.
 *     consumes:
 *       - multipart/form-data
 *     requestBody:
 *       required: true
 *       content:
 *         multipart/form-data:
 *           schema:
 *             type: object
 *             properties:
 *               file:
 *                 type: string
 *                 format: binary
 *                 description: The PDF or DOCX file to upload. Only one file per request.
 *     responses:
 *       201:
 *         description: File uploaded successfully and text extracted
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: success
 *                 message:
 *                   type: string
 *                   example: File uploaded successfully
 *                 file:
 *                   type: object
 *                   properties:
 *                     filename:
 *                       type: string
 *                     originalName:
 *                       type: string
 *                     size:
 *                       type: integer
 *                     mimetype:
 *                       type: string
 *                     path:
 *                       type: string
 *                     uploadTime:
 *                       type: string
 *                     extractedText:
 *                       type: string
 *                       description: The extracted plain text from the uploaded file. Empty if extraction failed.
 *                     contentExtractionError:
 *                       type: string
 *                       nullable: true
 *                       description: Error message if text extraction failed.
 *       400:
 *         description: Failed validation (e.g., missing file or unsupported filetype)
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: fail
 *                 message:
 *                   type: string
 *                   example: No file uploaded
 *       500:
 *         description: Server error (file upload or internal error)
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: error
 *                 message:
 *                   type: string
 */

// POST /upload (PDF/DOCX only)
router.post('/upload', upload.single('file'), uploadController.uploadFile);

/**
 * @swagger
 * /generate-mcqs:
 *   post:
 *     summary: Generate MCQs from text
 *     description: >
 *       Accepts plain text (e.g., extracted from study materials) and returns an array of MCQs generated by LLM/NLP API.
 *       Each MCQ includes a question, choices array, and correct answer field.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               text:
 *                 type: string
 *                 description: The extracted plain text from a study material. Minimum length: 50 chars recommended.
 *               maxQuestions:
 *                 type: integer
 *                 description: Maximum number of MCQs to generate (default 10, max 20)
 *               language:
 *                 type: string
 *                 description: Language for MCQs (default English)
 *             required:
 *               - text
 *     responses:
 *       200:
 *         description: MCQs generated successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: success
 *                 count:
 *                   type: integer
 *                   description: Number of MCQs generated and returned.
 *                 questions:
 *                   type: array
 *                   description: Array of MCQs
 *                   items:
 *                     type: object
 *                     properties:
 *                       question:
 *                         type: string
 *                       choices:
 *                         type: array
 *                         items:
 *                           type: string
 *                       answer:
 *                         type: string
 *         examples:
 *           application/json:
 *             value:
 *               status: success
 *               count: 2
 *               questions:
 *                 - question: "What is Newton's Second Law?"
 *                   choices: ["F = m/a", "F = ma", "E = mc^2", "V = IR"]
 *                   answer: "F = ma"
 *                 - question: "Who discovered gravity?"
 *                   choices: ["Newton", "Galileo", "Einstein", "Tesla"]
 *                   answer: "Newton"
 *       400:
 *         description: Invalid request body (missing or invalid text)
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: fail
 *                 message:
 *                   type: string
 *                   example: No text supplied for MCQ generation
 *       500:
 *         description: Downstream API, content, or internal server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: error
 *                 message:
 *                   type: string
 *                   example: Failed to generate MCQs
 */

/**
 * @swagger
 * /quiz/start:
 *   post:
 *     summary: Start a new quiz session
 *     description: Starts a quiz session with a list of MCQs. Returns a sessionId and the first question (without answer field).
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               questions:
 *                 type: array
 *                 items:
 *                   type: object
 *                   properties:
 *                     question:
 *                       type: string
 *                     choices:
 *                       type: array
 *                       items:
 *                         type: string
 *                     answer:
 *                       type: string
 *     responses:
 *       201:
 *         description: Quiz session started.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status: { type: string }
 *                 sessionId: { type: string }
 *                 question: { type: object }
 *                 questionIndex: { type: integer }
 *                 total: { type: integer }
 *       400: { description: Validation error }
 *       500: { description: Server error }
 */
router.post('/quiz/start', quizController.startQuizSession);

/**
 * @swagger
 * /quiz/{sessionId}/question:
 *   get:
 *     summary: Get current question for session
 *     parameters:
 *       - in: path
 *         name: sessionId
 *         required: true
 *         schema:
 *           type: string
 *         description: ID of the quiz session
 *     responses:
 *       200:
 *         description: Current question and progress
 *       400:
 *         description: Bad session or no more questions
 */
router.get('/quiz/:sessionId/question', quizController.getCurrentQuestion);

/**
 * @swagger
 * /quiz/{sessionId}/answer:
 *   post:
 *     summary: Answer current question
 *     parameters:
 *       - in: path
 *         name: sessionId
 *         required: true
 *         schema:
 *           type: string
 *         description: ID of session
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               choice:
 *                 type: string
 *     responses:
 *       200: { description: Answer feedback and optional next question/results }
 *       400: { description: Error }
 */
router.post('/quiz/:sessionId/answer', quizController.answerCurrentQuestion);

/**
 * @swagger
 * /quiz/{sessionId}/results:
 *   get:
 *     summary: Get results for quiz session
 *     parameters:
 *       - in: path
 *         name: sessionId
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       200: { description: Result summary }
 *       400: { description: Error }
 */
router.get('/quiz/:sessionId/results', quizController.getQuizResults);

// MCQ generation endpoint
router.post('/generate-mcqs', mcqController.generate);

module.exports = router;
